### ISSUE TITLE
namesdb is down, throwing 500 -- config error?

### ISSUE THREAD

**Issue by GeoffFroh** [densho/namesdb#4]
`https://ddr.densho.org/names` is throwing a 500 error. The app on stage is showing a transport error that suggests the namesdb app is attempting to use the ES index for the `ddr-public` app data, rather than the `namesdb` data.

```
TransportError(404, '{"_index":"ddrpublic-20180713a","_type":"_all","_id":"names","found":false}')
```

see: https://github.com/densho/ddr-public/130

**Comment by gjost** [comment]
This is a problem in [ddr-public](https://github.com/densho/ddr-public/issues/130) not with the namesdb app.
