### ISSUE TITLE
Multi term search works only with Boolean operators

### ISSUE THREAD

**Issue by sarabeckman** [densho/namesdb#5]
Names registry search on public website is not performing search for multi-term searches that do not include search Boolean operators "AND, OR, NOT". 

When a user searches terms: Hideo Hoshide or "Hideo Hoshide" no search results are returned.
When user searches term: Hoshide, 42 results are returned including 3 results for Hoshide, Hideo
When user searches term: Hideo, 1119 results are returned including 3 results for Hoside, Hideo
When user searches terms: Hideo AND Hoshide, 3 results are returned

**Comment by gjost** [comment]
I dug around for awhile and compared the search queries generated by the main ddrpublic app and the namesdb app.  They use the same `docstore` and `search` module code (namesdb literally imports the modules from ddrpublic) and the queries are basically identical except for the lists of fields and the aggregations (note: aggregations are applied AFTER the search is performed).

Pasting the search JSON generated by the namesdb app into the ElasticSearch Head app and looking at the results, I observe that in the NamesDB the records are more structured, with first name and last name as separate fields.  So the string "Hideo Hoshide" will not be found in any NamesDB data.

Doing the same with the ddrpublic search JSON shows that the string "Hideo Hoshide" appears as a phrase in various fields: title, description, display_name, persons, etc.

It looks like for namesdb we need to find a way to search across fields in a different way than ddrpublic.  I'll have to spend some time with the Elasticsearch docs...

**Comment by gjost** [comment]
Looks like we need to do a "multi_match" query instead of a "query_string" query.

Note: "multi_match" queries don't accept the "allow_leading_wildcard", "analyze_wildcard", and "default_operator" options.

**Comment by GeoffFroh** [comment]
Another possibility that may be much simpler would be to create a field that concatenates the first, last and other names fields into a single field that gets posted to the index.

**Comment by gjost** [comment]
I agree that throwing all the text in a big catch-all field is probably the way to go.  I put together a version of `Searcher.prepare` that can assemble a `multi_match` query if requested, but with Elasticsearch's `multi_match` you can no longer use boolean operators in the query.

**Comment by GeoffFroh** [comment]
We could also do that on the data side (i.e., in the import csvs).  Might be easier since it would only require a change to the defs and maybe some minor template tweaking.

**Comment by GeoffFroh** [comment]
The new import csvs have been pushed to the `namesdb-data` repo. There is now an `m_fullname` column that concatenates and lowercases the `m_firstname` and `m_lastname` columns

**Comment by gjost** [comment]
I modified `namesdb` to add a `search_text` field to the record model and to throw all the strings and anything that can be converted into a string in there.  I reindexed from the CSV files.  I modified the `ddrpublic` `names` app to add the `search_text` field to the search query, and it looks like it works.  You can search on `hideo hoshide` and you can also do searches like `hoshide tacoma` and get the sort of results you would expect.

**Comment by gjost** [comment]
Fixed in `namesdb` commit `af0ba85` for package `ddrpublic-develop_4.0.6~deb9`.

**Comment by sarabeckman** [comment]
Tested on ddrstage and it works.
